### ISSUE TITLE
Helps! Any video tutorial ?

### ISSUE THREAD

**Issue by iN3x0R** [cynical89/PokemonGO-Map-EasyStart#9]
Hey thank's for this great works, do you have any video for setup it from A to Z ? I'm a bit news on this and i don't undurstand everything.

**Comment by cynical89** [comment]
https://youtu.be/RJKAulPCkRI

That's the video for setting up the maps.

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

That's their wiki if you need more help there

https://github.com/cynical89/PokemonGO-Map-EasyStart/releases/tag/1.1.0

That's my latest build for my app. Extract the files and put it in the directory with the maps and launch.

**Comment by cynical89** [comment]
Also note issue #5 I'm making an installer for everything so it will automatically download the latest map, and install Python pip and all requirements

**Comment by iN3x0R** [comment]
Ok thans for fast answer:)
